name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - run: pip install -r requirements-dev.txt
      - run: pytest -v -x tests